
sudo: false # route build to the container-based infrastructure for a faster build

language: node_js
node_js:
  - "8"
  - "11"
  - "12"

cache:
  directories:
    - node_modules

env:
  global:
    - TZ="America/Los_Angeles" # for Headless Chrome. otherwise will be UTC, bad for tests

script: npm run ci
